// List of all possible maker activities
export const activities = [
    // Darkstar Chronicles Series
    "Darkstar Chronicles character miniatures",
    "Darkstar Chronicles vehicles (spaceships, rovers)",
    "Darkstar Chronicles alien creature models",
    "Modular terrain pieces for Darkstar Chronicles tabletop games",
    "Sci-fi themed building structures",
    "Robotic companions or drones",
    "Futuristic weapon props",
    "Sci-fi environment dioramas",
    "Customizable spaceship interior components",
    "Energy source props (crystals, power cells)",
    "Sci-fi communication devices",
    "Space station modules",
    "Planetary surface terrain models",
    "Alien artifacts",
    "Sci-fi tool sets",
    "Mecha models",
    "Modular space ship hull plates",
    "Sci-fi themed storage containers",
    "Display stands for Darkstar models",
    "Darkstar themed dice towers",

    // 3D Printing Projects
    "Customizable tool organizers",
    "Miniature building models (houses, castles)",
    "Fantasy creature miniatures (dragons, monsters)",
    "Functional household items (phone stands, hooks)",
    "Artistic sculptures",
    "Customizable dice sets",
    "Model kits (cars, planes)",
    "Decorative lamps",
    "Planters for small plants",
    "Puzzle boxes",
    "Customizable keychains",
    "Miniature terrain for fantasy games",
    "Architectural models",
    "Jewelry pieces",
    "Customizable game pieces",
    "Articulated models",
    "Complex gear systems",
    "Miniature tools",
    "Customizable storage boxes",
    "Display bases for miniatures",

    // Workshop & Tools
    "Custom tool holders",
    "3D printed jigs and fixtures",
    "Upgrades for 3D printers",
    "Custom enclosures for electronics",
    "Measuring tools (rulers, calipers)",
    "Workshop organization systems",
    "Custom knobs and handles",
    "Dust collection attachments",
    "Cable management solutions",
    "Electronic component enclosures",
    "Custom clamps",
    "Drill bit organizers",
    "Soldering station accessories",
    "Custom lighting fixtures",
    "Small parts organizers",
    "Tool modification parts",
    "Custom measuring guides",
    "Safety equipment add-ons",
    "Custom work bench tools",
    "3D printing filament storage solutions",

    // Gaming & Entertainment
    "Board game components",
    "Video game prop replicas",
    "Customizable controller accessories",
    "Display stands for video game consoles",
    "Cosplay props",
    "Miniature game scenery",
    "Customizable card holders",
    "Game token organizers",
    "Puzzle games",
    "Board game storage solutions",
    "Custom dice trays",
    "Miniature game terrain",
    "Customizable game boards",
    "Role playing game accessories",
    "Display cases for collectable items",

    // Art & Decoration
    "Abstract art pieces",
    "3D printed vases",
    "Wall art",
    "Custom light fixtures",
    "Decorative bookends",
    "Sculptural candle holders",
    "Customizable picture frames",
    "3D printed patterns",
    "Geometric art pieces",
    "Customizable signage",

    // Educational & Functional
    "Demonstrative mechanical models",
    "Anatomical models",
    "Custom enclosures for educational electronics",
    "3D printed tools for people with disabilities",
    "Architectural models for educational purposes",
    "Custom replacement parts",
    "Prototypes for new inventions",
    "Custom jigs for repair work",
    "3D printed teaching aids",
    "Custom adaptors",

    // Miscellaneous
    "Novelty items",
    "Customizable drink coasters",
    "Small robotic toys",
    "3D printed musical instruments",
    "Any item requested by the community",

    // CNC Projects
    "CNC machined terrain pieces",
    "CNC machined wooden boxes",
    "CNC machined custom signs",
    "CNC machined decorative panels",
    "CNC machined tool holders",
    "CNC machined furniture parts",
    "CNC machined custom inlays",
    "CNC machined game boards",
    "CNC machined enclosures for electronics",
    "CNC machined molds",

    // Additional Darkstar Chronicles Series
    "Darkstar Chronicles holographic displays",
    "Darkstar Chronicles medical equipment props",
    "Darkstar Chronicles military vehicles",
    "Darkstar Chronicles space station modules",
    "Darkstar Chronicles alien plant life",
    "Darkstar Chronicles cybernetic implants",
    "Darkstar Chronicles space suits",
    "Darkstar Chronicles control panels",
    "Darkstar Chronicles cargo containers",
    "Darkstar Chronicles defense turrets",
    "Darkstar Chronicles landing gear components",
    "Darkstar Chronicles habitat domes",
    "Darkstar Chronicles research equipment",
    "Darkstar Chronicles mining equipment",
    "Darkstar Chronicles space debris",

    // Additional 3D Printing Projects
    "Multi-part mechanical animals",
    "Interlocking geometric sculptures",
    "Customizable desk organizers",
    "Modular wall art systems",
    "Articulated dragon models",
    "Steampunk-themed accessories",
    "Miniature city building sets",
    "Custom action figure parts",
    "Mechanical clock components",
    "Interactive puzzle sculptures",
    "Customizable robot kits",
    "Architectural detail pieces",
    "Fantasy-themed bookends",
    "Modular terrain systems",
    "Custom game tokens",

    // Additional Workshop & Tools
    "Adjustable tool mounts",
    "Custom measuring templates",
    "Specialized cutting guides",
    "Modular storage drawers",
    "Tool calibration aids",
    "Custom workbench accessories",
    "Material feed guides",
    "Specialized clamping systems",
    "Tool maintenance stands",
    "Custom tool handles",
    "Workshop safety guards",
    "Material sorting systems",
    "Custom tool adapters",
    "Workshop ventilation components",
    "Tool upgrade kits",

    // Additional Gaming & Entertainment
    "Custom game dice towers",
    "Modular gaming terrain",
    "Character miniature bases",
    "Gaming accessory organizers",
    "Custom game piece holders",
    "Themed dice sets",
    "Gaming table accessories",
    "Card game organizers",
    "Miniature painting stands",
    "Gaming trophy designs",
    "Custom gaming tokens",
    "Game board overlays",
    "Miniature transport cases",
    "Gaming terrain accessories",
    "Custom gaming screens",

    // Additional Art & Decoration
    "Geometric wall sculptures",
    "Modular shelf systems",
    "Interactive art pieces",
    "Custom lamp shades",
    "Decorative wall panels",
    "3D printed mobiles",
    "Custom plant holders",
    "Artistic drawer pulls",
    "Decorative room dividers",
    "Custom mirror frames",
    "3D printed wind chimes",
    "Artistic door handles",
    "Custom light diffusers",
    "Decorative ceiling tiles",
    "3D printed fountains",

    // Additional Educational & Functional
    "Scientific demonstration models",
    "Mathematical visualization tools",
    "Custom laboratory equipment",
    "Educational puzzle sets",
    "Molecular structure models",
    "Engineering demonstration kits",
    "Custom measuring devices",
    "Educational display stands",
    "Interactive learning tools",
    "Custom storage solutions",

    // Additional CNC Projects
    "CNC machined puzzle boxes",
    "CNC machined wall art",
    "CNC machined desk accessories",
    "CNC machined machine parts",
    "CNC machined jewelry boxes",
    "CNC machined musical instruments",
    "CNC machined clock parts",
    "CNC machined model bases",
    "CNC machined tool handles",
    "CNC machined art frames",

    // Additional Miscellaneous
    "Custom phone stands",
    "Ergonomic computer accessories",
    "Unique desk organizers",
    "Custom keyboard parts",
    "3D printed camera accessories",
    "Custom tablet holders",
    "Unique cable management",
    "Custom speaker enclosures",
    "3D printed music stands",
    "Custom headphone stands",

    // Home & Living
    "Modular spice rack system",
    "Custom drawer organizers",
    "Wall-mounted key holders",
    "Floating shelf brackets",
    "Customizable coat hooks",
    "Bathroom accessories set",
    "Kitchen utensil holders",
    "Plant pot irrigation systems",
    "Door handle covers",
    "Window box planters",
    "Custom soap dishes",
    "Toothbrush holders",
    "Paper towel holders",
    "Adjustable tablet stands",
    "Remote control organizers",

    // Garden & Outdoor
    "Bird feeder designs",
    "Garden tool holders",
    "Plant markers and labels",
    "Rain gauge collectors",
    "Outdoor light fixtures",
    "Planter box systems",
    "Garden hose guides",
    "Composting bin parts",
    "Plant support structures",
    "Outdoor thermometer housing",
    "Garden edge markers",
    "Seed starting trays",
    "Plant propagation stations",
    "Garden decoration items",
    "Weather vane designs",

    // Office & Productivity
    "Monitor stand risers",
    "Custom pen holders",
    "Cable routing systems",
    "Desk drawer dividers",
    "Business card holders",
    "Paper organizers",
    "Laptop cooling stands",
    "Whiteboard marker holders",
    "Document sorting trays",
    "USB cable organizers",
    "Mouse cable holders",
    "Desk lamp parts",
    "Calculator stands",
    "Notebook holders",
    "Desk shelf systems",

    // Kitchen & Dining
    "Cookie cutter designs",
    "Custom measuring spoons",
    "Napkin holders",
    "Wine glass racks",
    "Kitchen roll dispensers",
    "Utensil drying racks",
    "Dish scrubber holders",
    "Recipe book stands",
    "Coffee pod organizers",
    "Tea bag holders",
    "Fridge organization bins",
    "Pantry label systems",
    "Fruit bowl designs",
    "Cup holder adapters",
    "Chopstick rests",

    // Hobby & Craft
    "Paint brush holders",
    "Craft supply organizers",
    "Yarn bowl designs",
    "Needle organizers",
    "Bead storage systems",
    "Drawing template guides",
    "Paper craft tools",
    "Craft paint racks",
    "Thread spool holders",
    "Craft knife holders",
    "Cutting mat storage",
    "Craft tool caddies",
    "Magnifying glass stands",
    "Craft light fixtures",
    "Project sorting bins",

    // Personal Accessories
    "Customizable jewelry boxes",
    "Sunglasses holders",
    "Watch display stands",
    "Belt organizers",
    "Tie rack designs",
    "Scarf hangers",
    "Makeup brush holders",
    "Jewelry display stands",
    "Hair accessory organizers",
    "Custom comb designs",
    "Ring holder dishes",
    "Glasses cleaning stations",
    "Personal care organizers",
    "Accessory travel cases",
    "Pocket item organizers",

    // Tech & Electronics
    "Raspberry Pi cases",
    "Arduino project enclosures",
    "Battery organizers",
    "Charging station docks",
    "Custom PCB enclosures",
    "LED strip diffusers",
    "Microcontroller mounts",
    "Sensor housing units",
    "Wire management clips",
    "Electronics project boxes"
]; 